name: barcelona
fileGroups:
  - Headers
  - project.yml
  - README.md
  - Makefile
  - Jenkinsfile
  - BUILDING.md
  - Scripts

options:
  deploymentTarget:
    macOS: 10.15
    iOS: 13.0
  defaultConfig: Debug
  bundleIdPrefix: com.barcelona
  createIntermediateGroups: true

packages:
  SwiftyJavaScriptCore:
    url: https://github.com/EricRabil/SwiftyJavaScriptCore
    from: 1.0.0
  SwiftCLI:
    url: https://github.com/jakeheis/SwiftCLI
    from: 6.0.3
  BarcelonaIPC:
    url: https://github.com/open-imcore/BarcelonaIPC
    from: 1.0.3
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 4.14.0
  Swime:
    url: https://github.com/sendyhalim/Swime
    from: 3.0.7
  Swog:
    url: https://github.com/EricRabil/Swog
    from: 1.0.2
  Pwomise:
    url: https://github.com/EricRabil/Pwomise
    from: 1.0.11
  BarcelonaFoundation:
    url: https://github.com/open-imcore/BarcelonaFoundation
    from: 1.0.2
  Gzip:
    url: https://github.com/1024jp/GzipSwift
    from: 5.1.1
  Noze:
    url: https://github.com/NozeIO/Noze.io
    from: 0.6.7
  Yammit:
    url: https://github.com/EricRabil/Yammit
    from: 1.0.0
  Swexy:
    url: https://github.com/EricRabil/Swexy
    from: 1.0.6
  SwiftyTextTable:
    url: https://github.com/scottrhoyt/SwiftyTextTable
    from: 0.9.0
  AnyCodable:
    url: https://github.com/Flight-School/AnyCodable
    from: 0.6.1
  InterposeKit:
    url: https://github.com/steipete/InterposeKit
    branch: master
  LineNoise:
    url: https://github.com/andybest/linenoise-swift
    from: 0.0.3
  FeatureFlags:
    url: https://github.com/EricRabil/FeatureFlags.swift
    from: 1.0.0

settings:
  base:
    AD_HOC_CODE_SIGNING_ALLOWED: YES
    FRAMEWORK_SEARCH_PATHS: $(PROJECT_DIR)/Frameworks
    CODE_SIGN_IDENTITY: "-"
    OTHER_SWIFT_FLAGS: "-Xcc -Wno-nullability-completeness -Xcc -Wno-incomplete-umbrella -Xcc -Wno-property-attribute-mismatch -Xcc -Wno-strict-prototypes -Xcc -Wno-arc-performSelector-leaks -Xcc -Wno-objc-protocol-method-implementation -Xcc -Wno-incomplete-umbrella -Xcc -Wno-visibility"
    WARNING_CFLAGS:
      - "-Wno-nullability-completeness"
      - "-Wno-incomplete-umbrella"
      - "-Wno-objc-protocol-method-implementation"
      - "-Wno-arc-performSelector-leaks"
      - "-Wno-strict-prototypes"
      - "-Wno-property-attribute-mismatch"
      - "-Wno-visibility"
    LD_RUNPATH_SEARCH_PATHS:
      - "$(inherited)"
      - "@executable_path/../Frameworks"
      - "@loader_path/Frameworks"
    SWIFT_VERSION: 5.0
    SKIP_INSTALL: YES
    SDKROOT: ""
    ALWAYS_SEARCH_USER_PATHS: NO
    ENABLE_HARDENED_RUNTIME: NO
    SYSTEM_FRAMEWORK_SEARCH_PATHS:
      - "$(inherited)"
      - "$(SDKROOT)$(SYSTEM_LIBRARY_DIR)/PrivateFrameworks"
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
    CODE_SIGNING_ALLOWED: YES
  configs:
    Debug:
      ONLY_ACTIVE_ARCH: YES
      GCC_OPTIMIZATION_LEVEL: 0
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS:
      - DEBUG
    Release:
      ONLY_ACTIVE_ARCH: NO
      SWIFT_OPTIMIZATION_LEVEL: "-Osize"

targets:
  # Core
  Barcelona:
    group: Core
    templates:
      - BLFramework
    sources:
      - Core/Barcelona
    dependencies:
      - package: Swime
      - package: AnyCodable
      - package: Gzip
      - package: InterposeKit
      - package: BarcelonaFoundation
      - package: Swog
      - package: Pwomise
      - package: FeatureFlags
      - target: BarcelonaDB
        embed: true
        link: true
  BarcelonaDB:
    group: Core
    templates:
      - BLFramework
    sources:
      - Core/BarcelonaDB
    dependencies:
      - package: GRDB
      - package: BarcelonaFoundation
  BarcelonaJS:
    group: Core
    templates:
      - BLFramework
    sources:
      - Core/BarcelonaJS
    dependencies:
      - package: BarcelonaIPC
      - package: BarcelonaFoundation
      - package: SwiftyJavaScriptCore
      - target: Barcelona
        embed: true
        link: true
  # Tools
  grapple:
    group: Tools
    type: tool
    platform: [macOS,iOS]
    platformSuffix: -${platform}
    productNameFromSettings: true
    sources:
      - Tools/grapple
    scheme: {}
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Tools/grapple/grapple.entitlements
        CODE_SIGN_IDENTITY: "-"
        SWIFT_OBJC_BRIDGING_HEADER: Tools/grapple/grapple.h
        PRODUCT_BUNDLE_IDENTIFIER: com.apple.iChat
        PRODUCT_NAME: grapple-${platform}
        PRODUCT_MODULE_NAME: grapple
    dependencies:
      - package: SwiftyTextTable
      - package: LineNoise
      - package: SwiftCLI
      - package: Yammit
      - target: Barcelona
        embed: true
        link: true
      - target: BarcelonaJS
        embed: true
        link: true
      - target: BarcelonaMautrixIPC
        embed: true
        link: true
  imserver:
    group: Tools
    type: tool
    platform: macOS
    scheme: {}
    sources:
      - Tools/imserver
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Beeper/barcelona-mautrix/barcelona-mautrix.entitlements
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_BUNDLE_IDENTIFIER: com.apple.imagent
    dependencies:
      - package: SwiftCLI
      - package: Noze
        product: http
      - package: Yammit
      - target: Barcelona
        embed: true
        link: true
  # Beeper
  BarcelonaMautrixIPC:
    group: Beeper
    templates:
      - BLFramework
    sources:
      - Beeper/BarcelonaMautrixIPC
    dependencies:
      - package: BarcelonaFoundation
      - target: Barcelona
        embed: true
        link: true
  barcelona-mautrix:
    group: Beeper
    type: tool
    platform: [macOS,iOS]
    platformSuffix: -${platform}
    productNameFromSettings: true
    scheme: {}
    sources:
      - Beeper/barcelona-mautrix
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Beeper/barcelona-mautrix/barcelona-mautrix.entitlements
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_BUNDLE_IDENTIFIER: com.apple.iChat
        PRODUCT_NAME: barcelona-mautrix-${platform}
        PRODUCT_MODULE_NAME: barcelona_mautrix
    dependencies:
      - target: Barcelona
        embed: true
        link: true
      - target: BarcelonaMautrixIPC
        embed: true
        link: true
      - target: BarcelonaJS
        embed: true
        link: true

schemes:
  tools:
    build:
      targets:
        barcelona-mautrix-macOS: [running]
        grapple-macOS: [running]
    run:
      executable: grapple
  ci-macos:
    build:
      targets:
        barcelona-mautrix-macOS: run
        grapple-macOS: run
  ci-ios:
    build:
      targets:
        barcelona-mautrix-iOS: run
        grapple-iOS: run

targetTemplates:
  BLFramework:
    type: framework
    platform: macOS
    settings:
      base:
        MACH_O_TYPE: staticlib
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        DEFINES_MODULE: YES
        PRODUCT_NAME: "$(TARGET_NAME:c99extidentifier)"
        VALID_ARCHS: "x86_64 arm64e arm64"
        SUPPORTED_PLATFORMS: "macosx iphonesimulator iphoneos"
