name: Builder

on:
  push:
    branches:
      - main

jobs:
  mac-builder:
    name: macOS Builder
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build macOS
        run: make macos

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS-build
          path: archive
  ios-builder:
    name: iOS Builder
    runs-on: macos-latest

    steps:
      - name: Setup Theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: 8771215f765e774bfefdacc6ddf0e151c2973d49
          path: theos
          submodules: recursive

      - name: What the hell is going on
        run: |
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/theos

      - name: Download SDKs
        run: |
          curl -LO https://github.com/xybp888/iOS-SDKs/archive/master.zip
          bsdtar --strip-components=1 -xf master.zip --directory $GITHUB_WORKSPACE/theos/sdks
          rm -f master.zip

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build iOS
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make ios

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iOS-build
          path: archive